import Head from 'next/head'
import HeaderComponent from '../components/Homepage/header-component'
import stylesHp from '../styles/Homepage/Homepage.module.css';
import {getAllHomepage, getHomepageById} from "../lib/Homepage/homepage-lib";
import Homepage from "../types/Homepage/homepage-type";
import FooterComponent from '../components/Homepage/footer-component';
import TalkTeaserComponent from '../components/Events/talkTeaser-component';
// import RecipeTeaserComponent from '../components/Recipe/recipeTeaser-component';
import Image from 'next/image'
import HeroBanner from '../components/Homepage/hero-banner';
import { HOMEPAGE_ID } from '../lib/Common/constants';
import { getEventById } from '../lib/Events/events-lib';
import Event from '../types/Events/events-type';
import RichText from '../components/Common/richText-component';

export async function getStaticProps({ preview = false}){
  const allHomepage = await getAllHomepage(preview);
  const homepage = await getHomepageById(HOMEPAGE_ID);
  const event = await getEventById('jueiqMy3nU-eldKYwkE2Kg');
  return{
      props: {allHomepage,homepage,event, preview},
      // Next.js will attempt to re-generate the page:
      // - When a request comes in
      // - At most once every 10 seconds
      revalidate: 10, //in seconds
  }
  
}

type Props = {
  allHomepage: Homepage[];
  homepage: Homepage;
  event: Event;
}

const Homepage = ({allHomepage,homepage,event}: Props) => {
 //const homepage = allHomepage[0];

  return (
    <div className={stylesHp.container}>
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={stylesHp.main}>
        <HeaderComponent 
          allHeaders={homepage.header}
        />
        <HeroBanner 
          heroImageUrl={event.eventImage?.results[0]?.fileUrl}
          altText=''
        />
       

        <div className={stylesHp.boxedContainer}>
          <h1 className={stylesHp.title}>
            {event.eventName}
          </h1>
          <RichText 
            richText={event.eventDescription} 
          />
        
          <TalkTeaserComponent
            allTalks={event.agenda}
          />
        </div>

      
        <FooterComponent
          allFooters={homepage.footer}
        />
        
        
      </main>

      
    </div>
  )
}
export default Homepage;